" pathogen
call pathogen#infect()
call pathogen#helptags()

" color stuffs
colorscheme badwolf
"colorscheme molokai
set background=dark
set t_Co=256

" basics
set number
syntax on
set nocompatible " with vi
set bs=2
set history=50
set ruler
set autoread
set linespace=0

" filetypes and auto indent
filetype on
filetype indent on
filetype plugin on

" highlight searches
set hlsearch

" show stuffs
set showmatch
set showmode

"  stuffs
set autoindent
set smartindent
set incsearch
set nobackup
set copyindent
set ignorecase

" tab things
set tabstop=2
set shiftwidth=2
set expandtab

set ts=2
set sw=2

" smart stuffs
set smartcase
set smarttab  " tabbing

" powerlines stuffs
set laststatus=2
set encoding=utf-8

" syntax highlighting?
au BufRead,BufNewFile Gemfile set filetype=ruby
au BufRead,BufNewFile *.md set filetype=markdown

" new things from http://statico.github.com/vim.html
:nmap \l :setlocal number!<CR>
:nmap \o :set paste!<CR>
:nmap \q :nohlsearch<CR> " turn off search highlighting 

" force hjkl navigation
"nnoremap <Left> :echoe "Use h"<CR>
"nnoremap <Right> :echoe "Use l"<CR>
"nnoremap <Up> :echoe "Use k"<CR>
"nnoremap <Down> :echoe "Use j"<CR>

" move up and down "graphical" lines
:nmap j gj
:nmap k gk

:map <Down> gj
:map <Up> gk
:imap <Down> <C-o>gj
:imap <Up> <C-o>gk

" move between buffers
:nmap <C-e> :e#<CR>
:nmap \n :bnext<CR>
:nmap \p :bprev<CR>

" ctrl-p stuffs
:let g:ctrlp_map = '<Leader>t'
:let g:ctrlp_match_window_bottom = 0
:let g:ctrlp_match_window_reversed = 0
:let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc)$|(^|[/\\])\.(hg|git|bzr)($|[/\\])|__init__\.py'
:let g:ctrlp_working_path_mode = 0
:let g:ctrlp_dotfiles = 0
:let g:ctrlp_switch_buffer = 0

" Why should I have to type :CtrlP?
:nmap <C-p> :CtrlPMixed<CR>

" NERDTree things
:nmap \e :NERDTreeToggle<CR>

" make split screens nicer
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright


set spell
"set tw=80
set wrap
set linebreak
set nolist

set colorcolumn=81 " 1 past 80...

" markin-downs, gitcommit, hgcommit
autocmd BufNewFile,BufRead *.md,*.markdown set tw=80


