# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="kennethreitz"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git mericurial rails ruby sublime vi-mode github gem archlinux pip python rvm rake rails3)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/core_perl:/home/don/.rvm/bin:/home/don/projects/chromium/depot_tools:/home/don/.gem/ruby/1.9.1/bin:/home/don/projects/chromium/depot_tools

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# set some variables?
export EDITOR="vim"
export LESS="-R"

# sudo aliases
alias pacman='sudo pacman-color'
alias pip='sudo pip'
alias pip2='sudo pip2'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown'
alias systemctl='sudo systemctl'

alias susu='sudo su -'

# other aliases
alias more='less'
alias open='xdg-open'
alias vba='VisualBoyAdvance'
alias dk2='ssh dkuntzco@dkuntz2.com'
alias vconsult='ssh vconsult@consultvelocity.com'

alias glog="git log --format='%Cgreen%h%Creset %C(cyan)%an%Creset - %s' --graph"

# color aliases
alias ls='ls -p --color=auto'
alias diff='colordiff'
alias grep='grep --color=auto'

# ls stuff
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# gem stuff
export GEM_HOME="~/.gem/ruby/1.9.1"
