#
# ~/.bashrc
#

# parse git branch
function pgb() {
		git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# include ~/.bash_colors for colors...
if [ -f ~/.bash_colors ]; then
    . ~/.bash_colors
fi

# locales
export LC_ALL=
export LC_COLLATE=C
export LANG=en_US.UTF-8

# color stuffs
alias ls='ls -p --color=auto'
alias diff='colordiff'
alias grep='grep --color=auto'

# ls stuffs
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

PS1='\[\u@\h:\W \$ \]'
PS1="\[$Blue\]\u\[$Color_Off\]@\[$Green\]\h\[$Color_Off\]:\[$Red\]\W\[$BBlack\]$(pgb)\[$Color_Off\] $ "


export LESS="-R"
export EDITOR="vim"

alias pacman='sudo pacman'
alias pip='sudo pip'
alias pip2='sudo pip2'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown'

alias su='sudo su -'

alias more='less'
alias open='xdg-open'
#alias mkdir='mkdir -p -v'
alias ..='cd ..'

# CUSTOM STUFFS
alias dk2='ssh dkuntzco@dkuntz2.com'
alias vconsult='ssh vconsult@consultvelocity.com'

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:$HOME/projects/chromium/depot_tools # add chromium depot_tools

# case correction
shopt -s nocaseglob

# history stuffs
shopt -s histappend
export HISTCONTROL=ignoreboth
export HISTSIZE=1000
export HISTFILESIZE=1000

alias vba='VisualBoyAdvance'

shopt -s checkwinsize


# because django likes it?
#export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# PRETTY GIT LOG
alias glog="git log --format='%Cgreen%h%Creset %C(cyan)%an%Creset - %s' --graph"
